version: '3.8'

services:
    rust_stable_toolchain:
        container_name: unspentio_data_generator_rust_stable_toolchain
        build:
            context: ./service/rust_stable_toolchain/
            dockerfile: dockerfile
        environment:
            USER: ${USER}
        volumes:
            - ./../../../../:/unspentio
        ports:
            - 80:80
        working_dir: /unspentio
        restart: always
        tty: true
        init: true

networks:
    default:
        name: resource
        driver: bridge