[tokio_runtime]

# It is better that the number be greater or equal to 512. It all depends on the workload
# of blocking tasks - these are tasks that take more than 1ms of CPU time.
[tokio_runtime.maximum_blocking_threads_quantity]
value = 16

# It is better that the number be equal to the number of threads that the hardware
# can handle simultaneously.
[tokio_runtime.worker_threads_quantity]
value = 4

# It is better that the number be greater or equal to 2MiB
[tokio_runtime.worker_thread_stack_size]
value = 2097152

[application_server]

[application_server.tcp]

[application_server.tcp.socket_address]
value = "0.0.0.0:80"

[application_server.tcp.nodelay]
value = false

[application_server.tcp.sleep_on_accept_errors]
value = false

[application_server.tcp.keepalive]

[application_server.tcp.keepalive.duration]
value = 3
is_exist = false

[application_server.tcp.keepalive.interval_duration]
value = 1
is_exist = false

[application_server.tcp.keepalive.retries_quantity]
value = 3
is_exist = false

[application_server.http]

[application_server.http.adaptive_window]
value = false

[application_server.http.connection_window_size]
value = 1048576    #1MB

[application_server.http.stream_window_size]
value = 1048576    #1MB

[application_server.http.maximum_frame_size]
value = 16384  #16KB

[application_server.http.maximum_sending_buffer_size]
value = 409600    #400KB

[application_server.http.enable_connect_protocol]
value = false

[application_server.http.maximum_header_list_size]
value = 1048576    #1MB

[application_server.http.maximum_pending_accept_reset_streams]
value = 20
is_exist = false

[application_server.http.keepalive]
is_exist = false

[application_server.http.keepalive.interval_duration]
value = 5

[application_server.http.keepalive.timeout_duration]
value = 20

[remote_service]

[remote_service.data_proxy]

[remote_service.data_proxy.url]
value = "https://preview-api-data-proxy.notspent.dev:443"

[remote_service.data_proxy.server_access_token]
value = "jsdcUISDcj0SUDJCojsSEcijcOSDI"

[remote_service.coingecko]

[remote_service.coingecko.pro]

[remote_service.coingecko.pro.api_key]
value = "ivalid_token_kdscSsckfssSDC"

[remote_service.coingecko.pro.url]
value = "https://pro-api.coingecko.com"

[logging]

[logging.directory_path]
value = "/_log"

[logging.file_name_prefix]
value = "log"

[security]

[security.server_access_token]
value = "qwerty"

[resource]

[resource.postgresql]

[resource.postgresql.configuration]
value = "host= port= user= password= dbname="

[task]

[task.generate_aggregated_balance_snapshot]

[task.generate_aggregated_balance_snapshot.cron_configuration]
value = "0 */10 * * * * *"

[task.generate_base_balance_snapshot]

[task.generate_base_balance_snapshot.cron_configuration]
value = "0 */10 * * * * *"

[task.update_assets___generate_asset_snapshot]

[task.update_assets___generate_asset_snapshot.cron_configuration]
value = "0 0 */1 * * * *"

[task.update_assets_for_subportfolio_trackable_wallet]

[task.update_assets_for_subportfolio_trackable_wallet.cron_configuration]
value = "0 */30 * * * * *"