[package]
name = "build_script_constant"
version = "0.1.0"
authors.workspace = true
edition = "2021"

[lib]
name = "build_script_constant"
path = "./mod.rs"
test = true
doctest = true
bench = true
doc = true
proc-macro = false
harness = true
edition = "2021"
crate-type = ["lib"]
required-features = []

[dependencies]

[features]
default = []